[package]
name = "iota_rspammer"
version = "0.1.1"
authors = ["Bernardo A. Rodrigues <bernardo.araujo@iota.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-client = { git = "https://github.com/iotaledger/iota.rs", branch = "dev" }
bee-message = { git = "https://github.com/iotaledger/bee", branch = "dev" }
tokio = { version = "1.0", features = ["macros", "sync", "time"] }
structopt = { version = "0.3", default-features = false }
url = "2.2.0"
rand = "0.8.3"
